name = "linear-algebra-done-right-lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LinearAlgebraDoneRightLean"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
linter.unusedVariables = true
maxSynthPendingDepth = 3
doc.verso = true
warn.sorry = false

[[require]]
name = "companion-helper"
git = "https://github.com/rkirov/companion-helper"
rev = "main"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "v4.30.0-rc2"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "LinearAlgebraDoneRightLean"
